name: Build

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  # Group by workflow, branch and PR number.
  # If the event is a merge group, use the merge group id as the PR number.
  # If it's not a PR or merge group, use 'main' as the PR number.
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.event.merge_group.id || 'main' }}
  # Cancel only in-progress jobs when it's a PR.
  cancel-in-progress: ${{ github.event_name == 'pull_request_target' || github.event_name == 'merge_group' }}

jobs:
  node-monorepo-stack:
    uses: abinnovision/actions/.github/workflows/workflow.yaml@node-monorepo-stack-dev
    secrets: inherit
    with:
      # Package publishing - disabled for now
      enable-package-publishing: false

      # Docker image builds - enabled only for main branch pushes
      enable-app-image-builds: true
      enable-apps-registry-ghcr: true
      enable-apps-registry-gcpar: true

      # GCP Artifact Registry configuration
      registry-gcpar-url: ${{ vars.GCP_AR_DOCKER_URL }}
      gcp-auth: ${{ vars.GCP_AUTH }}
